---
apiVersion: v1
kind: Secret
metadata:
  name: codimd-secrets
type: Opaque
stringData:
  POSTGRES_USER: "codimd"
  POSTGRES_PASSWORD: "postgres"
  CMD_DB_URL: "postgres://codimd:postgres@codimd-postgres-service:5432/codimd"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codimd-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codimd-postgres
  template:
    metadata:
      labels:
        app: codimd-postgres
    spec:
      containers:
      - name: codimd-postgres
        image: postgres:11.6-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: codimd-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: codimd-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: codimd-postgres-service
spec:
  selector:
    app: codimd-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codimd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codimd
  template:
    metadata:
      labels:
        app: codimd
    spec:
      containers:
      - name: codimd
        image: hackmdio/hackmd:2.4.2
        env:
        - name: CMD_DB_URL
          valueFrom:
            secretKeyRef:
              name: codimd-secrets
              key: CMD_DB_URL
        - name: CMD_USECDN
          value: "false"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: upload-data
          mountPath: /home/hackmd/app/public/uploads
      volumes:
      - name: upload-data
        persistentVolumeClaim:
          claimName: upload-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: codimd-service
spec:
  type: NodePort
  selector:
    app: codimd
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: upload-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

