apiVersion: apps/v1
kind: Deployment
metadata:
  name: memos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memos
  template:
    metadata:
      labels:
        app: memos
    spec:
      containers:
      - name: memos
        image: ghcr.io/usememos/memos:latest
        ports:
        - containerPort: 5230
        volumeMounts:
        - name: memos-data
          mountPath: /var/opt/memos
      volumes:
      - name: memos-data
        persistentVolumeClaim:
          claimName: memos-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memos-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: memos-service
spec:
  selector:
    app: memos
  ports:
    - protocol: TCP
      port: 5230
      targetPort: 5230
