apiVersion: apps/v1
kind: Deployment
metadata:
  name: pepe-deployment
spec:
  selector:
    matchLabels:
      app: pepe
  replicas: 1
  template:
    metadata:
      labels:
        app: pepe
    spec:
      containers:
      - name: pepe
        image: alexxi19/pepe-server:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: pepe
spec:
  selector:
    app: pepe
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000

